name: tempesta
description: A weather App in Flutter.

version: 1.0.0+1

environment:
  sdk: ">=2.13.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^0.1.2
  geolocator: ^7.4.0
  http: ^0.13.3
  flutter_spinkit: ^5.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
  - images/

  fonts:
  - family: Spartan MB
    fonts:
    - asset: fonts/SpartanMB-Black.otf
<<<<<<< HEAD
      weight: 900
=======
      weight: 900
>>>>>>> 7fba319c50cfb06dc33df8195a552137b581220f
